### ISSUE TITLE
Preferences and Categorising

### ISSUE THREAD

**Issue by mxhash** [NETWAYS/rt-extension-queuecategories#4]
Hi,

in our RT there is a problem with the categorising of the queues. A couple of them falls out of the order. Because the component has preferences saved for the users, maybe that's a pitfall for the list ordering.

@Al2Klimov can you have a quick look please?

Cheers,
Marius

**Comment by Al2Klimov** [comment]
Works for me. (Verified queues and categories order.) Neither @dnsmichi not @lippserd seem to know about this. IMO we should discuss this offline.

**Comment by Al2Klimov** [comment]
As discussed (offline) and reproduced:

This occurs only for queues visible only by a few users.
